name: formal_languages
description: Formal languages implementation.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.1.2
  test: ^1.21.0
